// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.AppView = (function(_super) {
    __extends(AppView, _super);

    function AppView() {
      return AppView.__super__.constructor.apply(this, arguments);
    }

    AppView.prototype.template = _.template('<h1>Blackjack</h1> <div class="new-game-container"></div> <div class="bet-container"></div> <div class="game-container"></div>');

    AppView.prototype.initialize = function() {
      this.model.on('newGame', this.render, this);
      return this.render();
    };

    AppView.prototype.render = function() {
      this.$el.children().detach();
      this.$el.html(this.template());
      this.$('.new-game-container').html(new NewGameView({
        model: this.model
      }).el);
      this.$('.bet-container').html(new BetView({
        model: this.model
      }).el);
      return this.$('.game-container').html(new GameView({
        model: this.model.get('game')
      }).el);
    };

    return AppView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=AppView.js.map
