// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.BetView = (function(_super) {
    __extends(BetView, _super);

    function BetView() {
      return BetView.__super__.constructor.apply(this, arguments);
    }

    BetView.prototype.template = _.template('<div>Chip Count: <%= chips %>, Current Bet: <%= bet %></div> <button class="raise">Raise Bet</button>');

    BetView.prototype.events = {
      'click .raise': function() {
        return this.model.raiseBet();
      }
    };

    BetView.prototype.initialize = function() {
      this.model.on('change', this.render, this);
      return this.render();
    };

    BetView.prototype.render = function() {
      this.$el.children().detach();
      return this.$el.html(this.template(this.model.attributes));
    };

    return BetView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=BetView.js.map
