// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.BlackjackView = (function(_super) {
    __extends(BlackjackView, _super);

    function BlackjackView() {
      return BlackjackView.__super__.constructor.apply(this, arguments);
    }

    return BlackjackView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=BlackjackView.js.map
