// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.NewGameView = (function(_super) {
    __extends(NewGameView, _super);

    function NewGameView() {
      return NewGameView.__super__.constructor.apply(this, arguments);
    }

    NewGameView.prototype.template = _.template('<div class="new-game-dialogue"> <h1>Start a New Game?</h1> <button class="new-game">Yes</button> </div>');

    NewGameView.prototype.events = {
      'click .new-game': function() {
        this.showGameView = false;
        this.render();
        return this.model.get('game').newGame();
      }
    };

    NewGameView.prototype.initialize = function() {
      this.model.on('gameOver', function() {
        this.showGameView = true;
        return this.render();
      }, this);
      return this.render();
    };

    NewGameView.prototype.render = function() {
      this.$el.children().detach();
      if (this.showGameView) {
        return this.$el.html(this.template());
      } else {
        return this.$el.html('');
      }
    };

    return NewGameView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=NewGameView.js.map
