// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Hand = (function(_super) {
    __extends(Hand, _super);

    function Hand() {
      return Hand.__super__.constructor.apply(this, arguments);
    }

    Hand.prototype.model = Card;

    Hand.prototype.initialize = function(array, deck, isDealer) {
      this.deck = deck;
      this.isDealer = isDealer;
    };

    Hand.prototype.hit = function() {
      var isOver, temp;
      isOver = _(this.scores()).every(function(score) {
        return score > 21;
      });
      if (!isOver) {
        temp = this.deck.pop();
        this.add(temp);
      }
      isOver = _(this.scores()).every(function(score) {
        return score > 21;
      });
      if (isOver) {
        this.trigger('over21', this);
      }
      return temp;
    };

    Hand.prototype.hasAce = function() {
      return this.reduce(function(memo, card) {
        return memo || (card.get('value') === 1 && card.get('revealed'));
      }, 0);
    };

    Hand.prototype.minScore = function() {
      return this.reduce(function(score, card) {
        return score + (card.get('revealed') ? card.get('value') : 0);
      }, 0);
    };

    Hand.prototype.scores = function() {
      return [this.minScore(), this.minScore() + 10 * this.hasAce()];
    };

    Hand.prototype.stand = function() {
      return this.trigger('stand', this);
    };

    Hand.prototype.reveal = function() {
      return this.forEach(function(card) {
        if (!card.get('revealed')) {
          return card.flip();
        }
      });
    };

    return Hand;

  })(Backbone.Collection);

}).call(this);

//# sourceMappingURL=Hand.js.map
